import org.junit.jupiter.api.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.jupiter.api.Assertions.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue( classUnderTest.someLibraryMethod(),"someLibraryMethod should return 'true'");
    }
}
